### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by smileisak** [jenkinsci/juseppe#36]
Hi,

In our company, we have a Jenkins instance with no Internet access. I want to put in place an update site for Jenkins locally using juseppe.

#### Running Juseppe

Running Juseppe in a docker container using this command:
` docker run  --name juseppe -d -v /tmp/plugins:/juseppe/plugins/ -p 8001:8080 -e JUSEPPE_BASE_URI=http://10.0.0.200:8001 lanwen/juseppe`

Juseppe is working file and i can access to update-center.json.

    http://10.0.0.200:8001/update-center.json

#### Configuring with Jenkins

![image](https://user-images.githubusercontent.com/3457118/31131643-fa0700da-a85a-11e7-8d3e-1a939df221ae.png)

#### Problem

But the problem is when i'm trying to integrate it with Jenkins running in another container, i have this error .

    Signature verification failed in update site 'juseppe' (show details)

**Comment by lanwen** [comment]
What version of Jenkins do you have?

**Comment by smileisak** [comment]
@lanwen I'm using Jenkins ver. 2.7.4. I copied the Cert from `http://10.0.0.200:8001/update-center.json` 

    {json value of signature.certificates[0] (without quotes)}

**Comment by lanwen** [comment]
Did you try to use constant certificate? It's strange - I have newer J and it works fine with the same setup... Also you can try to put this cert to special folder, as mentioned here: https://github.com/ikedam/backend-update-center2/wiki/How-to-create-your-own-Jenkins-Update-Center#put-your-certificate

Please write feedback after trying this workarounds

**Comment by smileisak** [comment]
Well, @lanwen after you requested modifications, i've used a newer version of Jenkins  `Jenkins ver. 2.60.3`.
1. * Made the requested configuration
2. * Configured Juseppe
3. * Configured the proxy access
4. * Installed UpdateSites Jenkins plugin
5. * Disabled default Jenkins UpdateSites
6. * Disabled proxy access
7. * Try to check for update sites

#### Result
Juseppe logs :+1: 

    2017-10-03 15:06:37 INFO  172.17.0.1 - - [1507043197715] "GET /update-center.json?id=juseppe&version=2.60.3 HTTP/1.1" 200 2825

Jenkins: 
![image](https://user-images.githubusercontent.com/3457118/31133506-08fec9ce-a860-11e7-855b-f7a9b226eafd.png)

I noticed that the only plugin provided by Juseppe instance is installed successfully :dancer: . But i have this Exception.

![image](https://user-images.githubusercontent.com/3457118/31133749-a07ffd40-a860-11e7-9fe6-0d6b6ae11b34.png)


Note: I'm behind a corporate proxy.

**Comment by lanwen** [comment]
How did you disable default Jenkins UpdateSites? This looks like you filled it with empty url, so now it says that can't check default UpdSite with empty url. You can try to fill juseppe url as default Update Site too.

**Comment by smileisak** [comment]
@lanwen Yes, i filled it with empty string.

**Comment by smileisak** [comment]
When i fill the default UpdateSite url with juseppe one, it will cause the same problem.

    Signature verification failed in update site 'default' (show details)

**Comment by lanwen** [comment]
And the separate juseppe still works?

**Comment by lanwen** [comment]
So I dunno how to help with exception :( It seems that current configuration is the most appropriate :)

**Comment by Abubakar22** [comment]
I have removed the default update site and left i empty. I gave juseppe site as other sites. 

![juseppe 1](https://user-images.githubusercontent.com/17588727/32282412-e6897390-bef7-11e7-8d63-0691e3115ff4.JPG)

But still i can see all the available plugins and i can download and install all the plugins. as shown below. Can you help me regarding this

![juseppe2](https://user-images.githubusercontent.com/17588727/32282458-fc33e676-bef7-11e7-8cb6-375a17930c35.JPG)

**Comment by lanwen** [comment]
I think it caches the last fetch somewhere. So you could try to find something about update sites in the homedir of jenkins
