### ISSUE TITLE
Can't run Juseppe on localhost

### ISSUE THREAD

**Issue by mfuxi** [jenkinsci/juseppe#43]
I followed the basic steps of raising Juseppe using this command:
`docker run --init --name juseppe -v /juseppe/:/juseppe/plugins/ -e JUSEPPE_BASE_URI=http://my.company.com -p 80:8080 lanwen/juseppe
`
The container is running and I see the message:
UpdateSite will be available at http://my.company.com/update-center.json

But when I try to browse to http://127.0.0.1/update-center.json or the URL above I see nothing..

What am I missing here?

Thanks!

**Comment by sathomps** [comment]
I know that localhost should resolve to 127.0.0.1 but have you tried that?
 http://localhost/update-center.json

You can also specify the host that juseppe binds to using the following param

JUSEPPE_BIND_HOST (juseppe.jetty.host)

**Comment by mordf** [comment]
I tried 127.0.0.1 and also tried giving JUSEPPE_BIND_HOST localhost and 127.0.0.1

**Comment by mfuxi** [comment]
Tried 127.0.0.1 as well and it didn't work, also tried to pass the JUSEPPE_BIND_HOST var and it also didn't work..

Does it work for you?

**Comment by sathomps** [comment]
I haven't tried running it via docker.  There was an issue with the docker build on the previous merge due to tests failing.  

Let me try and get another clean docker build to run and I'll test it out locally.

@lanwen can you give me admin rights to the project?  If you don't have time nor the desire to maintain this anymore it'd be easier then me forking it and figuring out all the hooks.

**Comment by lanwen** [comment]
probably we should ask @jenkinsci about moving this project into this org where anyone can get admin right and maintain it properly. Fow now please just turn off tests on package phase and I'll retrigger the build

**Comment by sathomps** [comment]
Pull request has been created #3.  It looks like I no longer have write access so if you could merge that it would be appreciated.

Do you want to initiate the conversation with @jenkinsci so we can get this project in a state where others can contribute?

**Comment by sathomps** [comment]
Let me redo that merge request - something bad happened.

**Comment by lanwen** [comment]
@sathomps you have collaborator badge which means you have write access. I'll really appreciate if you will start this thread on jenkins-dev group

**Comment by sathomps** [comment]
Ok somehow I screwed up the merge request and it was pulling from the original fork.  I'll redo it and then start up the conversation.  Thanks for your help.

**Comment by sathomps** [comment]
The Docker image was built successfully

https://hub.docker.com/r/lanwen/juseppe/builds/bgtw8cadyb6vn2dzdcpjudi/

Want to try and install & run it again?  I'm currently trying to configure Docker on Windows 10 using WSL to test it myself.

**Comment by sathomps** [comment]
@lanwen  Before I post anything on the jenkins-dev group, I wanted to make sure you're aware that Jenkins does support internal update sites but you have to pay for it.  I don't see this getting official support as they know it's a necessity and want people to pay for it - nothing wrong with that.

https://www.cloudbees.com/products/cloudbees-jenkins-platform/enterprise-edition/features/custom-update-center-plugin

**Comment by lanwen** [comment]
Thats another thing. Its cloudbees platform based on jenkins. Thats unrelated to whats happening in jenkinsci org and jenkins-dev group

**Comment by sathomps** [comment]
I guess we'll see what kind of response comes back as there's some overlap between the two.

**Comment by mfuxi** [comment]
Pulled the latest image and still doesn't work, from within the container everything is working fine if I type the following command:
`curl http://localhost:8080/update-center.json`
I'm getting the .json in the terminal.

BTW: If I `docker inspect <containerID>` and I use the IPAddress which is written there still nothing happens.

**Comment by lanwen** [comment]
There is issue on your side with mapping if it works properly within container

**Comment by mfuxi** [comment]
OK, if I add to the docker run command from the README: `docker run --name juseppe --network=host -v /your/plugins/dir/:/juseppe/plugins/ -e JUSEPPE_BASE_URI=http://my.company.com -p 80:8080 lanwen/juseppe`

added: --network=host

Everything is working, but i'm not sure that's how it's supposed to be.

**Comment by sathomps** [comment]
Closing - please reopen if needed.
